/*
 * This file is generated by jOOQ.
*/
package org.tim.notes.data.jooq;


import javax.annotation.Generated;

import org.tim.notes.data.jooq.tables.FlywaySchemaHistory;
import org.tim.notes.data.jooq.tables.Notes;
import org.tim.notes.data.jooq.tables.Users;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = org.tim.notes.data.jooq.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.notes</code>.
     */
    public static final Notes NOTES = org.tim.notes.data.jooq.tables.Notes.NOTES;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = org.tim.notes.data.jooq.tables.Users.USERS;
}
